<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title>TimeCop</title>
        <meta name="description" content="Time Tracker Description" />
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="author" content="JacquetteLabs" />
        <meta name="keyword" content="Time, Track, Consultant, eHour, Expense, Hours, Billable" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <meta name="theme-color" content="#000000" />

        <link rel="stylesheet" href="styles/app.css" />
    </head>
    <body>


        <script type="text/javascript" src="scripts/app.includes.js"></script>
        <script type="text/javascript" src="scripts/app.js"></script>
    </body>
</html>
